{% set name = "pvmail" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec24fbda9043c937fd07d0589f52b0fb424cf6ba5389f770d9ae7304f7fca255

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - pvMail = PvMail.cli:main
    - pvMail_mail_test = PvMail.mailer:main
    - pvMail_mail_config_file = PvMail.ini_config:main
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64.0
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - pydm
    - pyepics
    - pyqt =5

test:
  imports:
    - PvMail
  commands:
    - pip  check
    - pvMail
    - pvMail -h
    - pvMail -v
    - pvMail_mail_test -h
    - pvMail_mail_config_file
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://BCDA-APS.github.io/pvMail
  summary: Watches an EPICS PV and sends email when value changes from 0 to 1.
  license: BSD-4-Clause
  license_file: src/PvMail/LICENSE
  doc_url: https://BCDA-APS.github.io/pvMail
  dev_url: https://github.com/BCDA-APS/pvMail

extra:
  recipe-maintainers:
    - prjemian
